Fix minor typos in Debian packaging files

diff --git a/debian/mariadb-server-core.postinst b/debian/mariadb-server-core.postinst
--- a/debian/mariadb-server-core.postinst
+++ b/debian/mariadb-server-core.postinst
@@ -30,7 +30,7 @@ case "$1" in
     then
       if ! setcap cap_ipc_lock+ep "$PROGRAM"
       then
-        echo "Setcap failed on $PROGRAM, required with --memlock if insufficent RLIMIT_MEMLOCK" >&2
+        echo "Setcap failed on $PROGRAM, required with --memlock if insufficient RLIMIT_MEMLOCK" >&2
       fi
     fi
     ;;
